### ISSUE TITLE
Problem when running with combination of wav2vec2 model and 4-grams LM

### ISSUE THREAD

**Issue by salforis** [oliverguhr/wav2vec2-live#10]
Hello. I'm using your code with model saved in local directory (model is downloaded from [here](https://huggingface.co/nguyenvulebinh/wav2vec2-base-vietnamese-250h)). We can use this model with or without 4-gram LM.
When i use model without LM, everything is ok. 
But when i use model with 4-gram LM (code for combination of wav2vec2 and 4-grams LM is [here](https://colab.research.google.com/drive/1pVBY46gSoWer2vDf0XmZ6uNV3d8lrMxx?usp=sharing)), there is error when running `kenlm.model(n_gram_path)`:
`OSError: [Errno -9981] Input overflowed`
Can you please check your code for this error?
Sorry for my bad English

**Comment by oliverguhr** [comment]
I just merged @voidful PR. This should solve your issue. 

Can you check this?

**Comment by salforis** [comment]
it worked now. just need better hardware
