### ISSUE TITLE
break in little pause

### ISSUE THREAD

**Issue by Siyamfahad** [oliverguhr/wav2vec2-live#11]
i am using the default code, but it looks like taking command very fast if I take a little pause it breaks the line and and prints it the
 next line for example if i speak "how are you" its taking "how" then "are " in the next line,,,,
 i can i reduce sensetivity of taking command??

**Comment by voidful** [comment]
You can change the threshold here: https://github.com/oliverguhr/wav2vec2-live/blob/a22f099010820776cf179a3d142411243b392d94/live_asr.py#L39

the value of vad is 

> an integer between 0 and 3. 0 is the least aggressive about filtering out non-speech, 3 is the most aggressive. (You can also set the mode when you create the VAD, e.g. vad = webrtcvad.Vad(3)):

refer to here:
https://github.com/wiseman/py-webrtcvad#how-to-use-it

**Comment by oliverguhr** [comment]
Thanks @voidful! Did that solve your problem @Siyamfahad?
