### ISSUE TITLE
Live ASR Engine with whisper 

### ISSUE THREAD

**Issue by Dimlight** [oliverguhr/wav2vec2-live#14]
I have implemented (not from scratch) LiveASREngine using whisper using the following codebase written by you:

https://github.com/oliverguhr/wav2vec2-live

The only change I made was in the wav2vec2_inference.py: initialized whisper model with hugging face pipeline.
my code: https://github.com/Dimlight/LiveASREngine
The problem I am facing now:

If I do not say anything and the entire room is silent, the engine continuously prints "you" or "thank you", I tested the system in a quiet room. still getting the same issue.

Can anyone please help me what can be the reasons for getting this kind of result?

**Comment by oliverguhr** [comment]
Thanks @Dimlight for the idea!

Did you try to use "[live_vad_asr.py](https://github.com/Dimlight/LiveASREngine/blob/main/live_vad_asr.py)" instead of the "[live_asr.py](https://github.com/Dimlight/LiveASREngine/blob/main/live_asr.py)"?

**Comment by Dimlight** [comment]
Thank you @oliverguhr I will try and I will let you know.
