### ISSUE TITLE
use it with local model

### ISSUE THREAD

**Issue by Salama1429** [oliverguhr/wav2vec2-live#15]
thanks a lot for your efforts, could you please tell me how I can use it with a local model on my computer (without uploading the model to hugging face)? , it's giving me this error message 
`ValueError: too many values to unpack (expected 3) `
![image](https://user-images.githubusercontent.com/95621539/201626372-118cb355-a03e-44c3-b33c-f9b966d4466c.png)

**Comment by oliverguhr** [comment]
Technically you just need to provide the path to the folder that contains you model. Looks like there is an issue with path or your private model. You can use VS Codes debugger to step into get_last_text and trace the issue.

**Comment by kabayan** [comment]
try:        
    while True:
        ret = asr.get_last_text()                        
        # text,sample_length = asr.get_last_text()                        
        # print(f"{sample_length:.3f}s"
        # # +f"\t{inference_time:.3f}s"
        # +f"\t{text}")
        print(ret[0])

except KeyboardInterrupt:   
    asr.stop()  

Set breakpoint at print and check ret valuable.
