### ISSUE TITLE
Optimisation for GPU with CUDA

### ISSUE THREAD

**Issue by merlenchanteur** [oliverguhr/wav2vec2-live#8]
Hello @oliverguhr ! Thank you for your code, which is working fine on my CPU.
For practical reasons (another device with poor CPU but good GPU), I would like to be able to run it on GPU, using CUDA. The problem is that when I run the code using
```
device = "cuda:0" if torch.cuda.is_available() else "cpu"
self.model.to(device)
```
I get a `RuntimeError: CUDA error: out of memory` error, even though I have 2GB memory available, and even though your code already uses `with torch.no_grad()`:.

Do you know if the code can be adapted to use less memory, or how much memory would be needed for an inference?

**Comment by oliverguhr** [comment]
2GB is most likely too small for a wave2vec-large model. You could try the smaller base model: facebook/wav2vec2-base-960h

**Comment by merlenchanteur** [comment]
Indeed, with the other model the code is able to run on my GPU! Thanks a lot!
