### ISSUE TITLE
Performance is not good, only for me?

### ISSUE THREAD

**Issue by BattashB** [oliverguhr/wav2vec2-live#9]
Hi , I'm using the code given, no errors, only one warning, but the performance is  terrible, am I the only one experincing that issues?
Buy terrible I mean it is **mostly hard to see the connection between what said and the transcription.**
The warning I'm getting is:
`Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-large-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.`

Any idea someone?

**Comment by oliverguhr** [comment]
Feel free to reopen this if needed.
